---
title: "Getting Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
`medinetparser` is a package meant to facilitate analysis of schedules generated by the Medinet Scheduling system, developed by [Medical Networks Scandinavia AB](https://www.medinetworks.se), for analysis in R, aiding scheduling and follow up. This project is in no way connected to the developers of Medinet.

## Installing the *medinetparser* Package

Chances are you will already have finished installing the `medinetparser` package, as you are reading this vignette. But just as a quick recap, this is how you install the package from GitHub.

1. Install *devtools*
```r
install.packages('devtools')
```
2. Load *devtools*
```r
library(devtools)
```
3. Install *medinetparser*
```r
install_github('JonasEngstrom/medinetparser', build_vignettes = TRUE)
```
4. Load *medinetparser*
```r
library(medinetparser)
```

## Get Started Using the Medinet Parser

Medinet Parser currently does not support scraping data directly from Medinet, as this would require handling login credentials. Therefore data must first be downloaded manually, by following the subsequent steps.

1. Go to the [Medinet Website](https://medinet.se).

2. Log in.

3. If you work in several departments, you will be prompted to choose one at this point. If not, skip ahead to the next step.

4. Click *Schema*.

5. Make sure *Schemavy* is set to *Vecka vs användare*.

6. Choose the weeks you are interested in analyzing.

7. Use the web brower’s save command.

8. Save the page in HTML format. This will be your input file to Medinet Parser.

## Loading Schedule in R

To load a Medinet schedule in R, use the function `load_tidy_schedule()`. It takes a file path as an argument and returns a tibble.

```r
my_loaded_schedule <- load_tidy_schedule('./medinetschedule.html')
```

The tibble can then be used with all the standard tidverse functions.

## Tallying Shifts

To quickly get an overview of the distribution of shifts per doctor the `tally_shifts()`function can be used to return a tally table. Note that the schedule first has to be loaded using the `my_loaded_schedule()` function.

```r
tally_table <- tally_shifts(my_loaded_schedule)
```
