#' Decode Categories
#'
#' Decodes categories encoded by `encode_categories()`, using a key generated by `make_prime_keys()`.
#'
#' @param encoded_values Values encoded by `encode_categories()`.
#' @param prime_keys Keys generated by `make_prime_keys()`.
#'
#' @return A list of lists with decoded categories.
#' @export
#' @seealso [medinetparser::encode_categories()], [medinetparser::make_prime_kesy()]
#' @md
#'
#' @examples
#' list_of_lists <- decode_categories(encoded_values, prime_keys)
decode_categories <- function(encoded_values, prime_keys) {
  encoded_values %>%
    purrr::map(function(x) names(prime_keys)[x %% prime_keys == 0]) %>%
    return()
}
