#' Sample Shifts
#'
#' Draws a number of samples from a tibble generated by the medinetparser
#' package, to check against the original Medinet schedule. This function is
#' meant to facilitate verifying data accuracy before further analysis. The
#' reason for this being that Medinet can be configured in different ways
#' in different departments. During development medinetparser has been
#' tested against schedules in two departments in separate hospitals, but
#' compatibility with every possible configuration cannot be guaranteed,
#' so checking tibbles generated by medinetparser against your own
#' department’s schedule is recommended.
#'
#' @param schedule_tibble A schedule tibble generated by
#'   `load_tidy_schedule()`.
#' @param samples The number of samples wanted. Defaults to ten.
#'
#' @return A tibble of samples.
#' @export
#' @seealso [medinetparser::load_tidy_schedule()]
#' @md
#'
#' @examples
#' sample_of_shifts <- sample_shifts(schedule_tibble)
sample_shifts <- function(schedule_tibble, samples = 10) {
  return_table <- tibble::tibble()

  for (i in 1:samples) {
    sampled_doctor <- schedule_tibble %>%
      dplyr::select(doctor_name) %>%
      dplyr::pull() %>%
      sample(1)

    sampled_date <- schedule_tibble %>%
      dplyr::filter(doctor_name == sampled_doctor) %>%
      dplyr::select(date) %>%
      dplyr::pull() %>%
      sample(1)

    return_table <- return_table %>%
      dplyr::bind_rows(
        schedule_tibble %>% filter(doctor_name == sampled_doctor & date == sampled_date))
  }

  return_table %>%
    dplyr::arrange(date, doctor_name) %>%
    return()
}
