#' Sample Shifts
#'
#' Draw a number of samples from a tibble generated by the medinetparser
#' package, to check against the original Medinet schedule. This function is
#' meant to facilitate verifying data accuracy before further analysis.
#'
#' @param schedule_tibble A schedule tibble generated by
#'   `extract_tidy_schedule()`.
#' @param samples The number of samples wanted. Defaults to ten.
#'
#' @return A tibble of samples.
#' @export
#' @seealso [medinetparser::extract_tidy_schedule()]
#' @md
#'
#' @examples
#' sample_of_shifts <- sample_shifts(schedule_tibble)
sample_shifts <- function(schedule_tibble, samples = 10) {
  return_table <- tibble::tibble()

  for (i in 1:samples) {
    sampled_doctor <- schedule_tibble %>%
      dplyr::select(doctor) %>%
      dplyr::pull() %>%
      sample(1)

    sampled_date <- schedule_tibble %>%
      dplyr::filter(doctor == sampled_doctor) %>%
      dplyr::select(date) %>%
      dplyr::pull() %>%
      sample(1)

    return_table <- return_table %>%
      dplyr::bind_rows(
        schedule_tibble %>% filter(doctor == sampled_doctor & date == sampled_date))
  }

  return_table %>%
    dplyr::arrange(date, doctor) %>%
    return()
}
