#' Tally Shifts
#'
#' Takes a tidy schedule generated by `load_tidy_schedule()` and generates a
#' table of shift tallies per doctor.
#'
#' @param tidy_schedule A tibble generated by `load_tidy_schedule()`.
#'
#' @return A tibble with tallies of shift types per doctor.
#' @export
#' @seealso [medinetparser::load_tidy_schedule()]
#' @md
#'
#' @importFrom magrittr "%>%"
#' @importFrom rlang .data
#'
#' @examples
#' tally_table <- tally_shifts(example_schedule)
tally_shifts <- function(tidy_schedule) {
  tidy_schedule %>%
    dplyr::group_by(.data$doctor_name, .data$shift_type) %>%
    dplyr::tally() %>%
    tidyr::pivot_wider(names_from = .data$shift_type, values_from = .data$n) %>%
    dplyr::mutate(dplyr::across(dplyr::everything(), ~ tidyr::replace_na(.x, 0))) %>%
    return()
}
