#' Tidy Schedule Row
#'
#' Takes a row from the schedule, as extracted from `extract_table()`, prime number encoding keys, as generated by `make_prime_keys()`, and a list of dates, as generated by `extract_dates()`. Returns a tibble with three columns; date, doctor, and shift_type.
#'
#' @param schedule_row A row from `extract_table()`.
#' @param encoding_keys Encoding keys from `make_prime_keys()`.
#' @param schedule_dates Dates from `extract_dates()`.
#'
#' @return A three column tibble.
#' @export
#' @seealso [medinetparser::extract_table()], [medinetparser::make_prime_keys()], [medinetparser::extract_dates()]
#' @md
#'
#' @examples
#' tidy_row <- tidy_schedule_row(row, keys, dates)
tidy_schedule_row <- function(schedule_row, encoding_keys, schedule_dates) {
  rearranged_table <- schedule_row %>%
    dplyr::mutate(dplyr::across(
      dplyr::everything(),
      function(x) medinetparser::encode_categories(x, encoding_keys)
      )) %>%
    tidyr::pivot_longer(dplyr::everything()) %>%
    dplyr::mutate(decoded = medinetparser::decode_categories(
      value,
      encoding_keys
      )) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(size = length(decoded)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(size = ifelse(size == 1, 0, size)) %>%
    dplyr::mutate(counter = ifelse(size > 0, 2, 1))

  max_categories <- rearranged_table %>%
    dplyr::select(size) %>%
    max()

  return_table <- rearranged_table %>%
    dplyr::slice(1:(max_categories+1)) %>%
    dplyr::mutate(value = -1, size = 0) %>%
    dplyr::bind_rows(rearranged_table)

  for (i in 1:max_categories) {
    return_table <- return_table %>%
      dplyr::mutate(size = ifelse(dplyr::lag(size) > 0,
                                  dplyr::lag(size) - 1,
                                  size))
    }

  return_table %>%
    dplyr::mutate(size = dplyr::lag(size)) %>%
    dplyr::filter(value != -1, size == 0) %>%
    tidyr::uncount(counter) %>%
    dplyr::filter(dplyr::row_number() %% 2 == 0) %>%
    dplyr::mutate(doctor = dplyr::slice(return_table, 1) %>% dplyr::pull(decoded)) %>%
    dplyr::slice(2:n()) %>%
    dplyr::slice(1:dplyr::pull(dplyr::count(schedule_dates))) %>%
    dplyr::bind_cols(schedule_dates) %>%
    dplyr::select(-name, -value, -size) %>%
    dplyr::relocate(date, doctor, shift_type = decoded) %>%
    tidyr::unnest(c(shift_type, doctor)) %>%
    dplyr::mutate(across(c(doctor, shift_type), forcats::as_factor)) %>%
    return()
}
